services:
  boreal.chat:
    image: ghcr.io/wosherco/boreal.chat
    ports:
      - 3000:3000
    environment:
      PUBLIC_ENVIRONMENT: production
      PUBLIC_URL: https://boreal.chat
      PUBLIC_SENTRY_DSN: ""
      GOOGLE_AUTH_CLIENT_ID: ""
      GOOGLE_AUTH_CLIENT_SECRET: ""
      GOOGLE_AUTH_REDIRECT_URI: "https://boreal.chat/auth/google/callback"
      DATABASE_URL: "postgres://postgres:password@postgres:5432/borealchat"
      ELECTRIC_SQL_URL: "http://electric:3000"
    volumes:
      - .env:/app/.env

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: borealchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/borealchat?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - 3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
